"""enlarge assets.codec for RunPod UploadId

Revision ID: e35402836b51
Revises: 0f1518859de0
Create Date: 2026-08-12 19:53:03.336624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35402836b51'
down_revision: Union[str, Sequence[str], None] = '0f1518859de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("assets", "codec", existing_type=sa.String(length=50), type_=sa.String(length=500), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("assets", "codec", existing_type=sa.String(length=500), type_=sa.String(length=50), existing_nullable=True)
    # ### end Alembic commands ###
